from datetime import *
nowh = datetime.now()
print(nowh)
now = date.today()
print(now)
print(now.day)
nowl = datetime(year = 2022 , month = 9, day = 24 , hour = 12, minute = 30, second = 0)
print(nowl)
print(nowl.day)
print(nowh - nowl)
